app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as'=>'home','uses'=>'HomeController@index']);

Route::get('about-us', function () {
    return view('pages.about-us.index');
});


Route::get('request-appointment', ['as'=>'appointment.index','uses'=>'AppointmentController@index']);
Route::post('appointment/store', ['as'=>'appointment.request','uses'=>'AppointmentController@store']);

Route::post('search',['as'=>'search','uses'=>'SearchController@search'] );
Route::post('search-service',['as'=>'search.service','uses'=>'SearchController@searchService'] );

/**
 * API Routes
 */

Route::group(['prefix' => 'find-a-doctor'], function() {
    Route::get('/',['as'=>'physician.index','uses'=>'PhysicianController@index']);
    Route::get('/{doctor_slug}',['as'=>'physician.single','uses'=>'PhysicianController@single']);
});


Route::group(['prefix' => 'clinical-services'], function() {
    Route::get('/', ['as' => 'department.index', 'uses' => 'DepartmentController@index']);
    Route::get('/{department_slug}', ['as' => 'department.single', 'uses' => 'DepartmentController@single']);
});


Route::group(['prefix' => 'patients'], function() {
    Route::get('/', function () { return view('pages.patients.services'); });
    Route::get('/our-services', function () { return view('pages.patients.services'); });
    Route::get('/insurance', function () { return view('pages.patients.insurance'); });
    Route::get('/at-healthpoint', function () { return view('pages.patients.at-healthpoint'); });

    Route::group(['prefix' => 'newsletters'], function() {
        Route::get('/',['as'=>'media.patient-newsletters','uses'=>'MediaController@newsletters']);
        Route::get('/{slug}',['as'=>'media.patient-newsletters.single','uses'=>'MediaController@singleNewsletter']);
    });

});


Route::group(['prefix' => 'health-tips'], function() {
    Route::get('/',['as'=>'blog.index','uses'=>'BlogController@index']);
    Route::get('/{article_id}',['as'=>'blog.single','uses'=>'BlogController@single']);
});

Route::get('page/{slug}',['as'=>'pages.single','uses'=>'PageController@article']);

Route::group(['prefix' => 'work-with-us'], function() {

    Route::get('/', function () { return view('pages.work-with-us.working-for-healthpoint'); });
    Route::get('/emiratization', function () { return view('pages.work-with-us.emiratization'); });
    Route::get('/careers', function () { return view('pages.work-with-us.opportunities'); });
});


Route::group(['prefix' => 'media'], function() {

    Route::get('/news',['as'=>'media.news','uses'=>'MediaController@news']);
    Route::get('/news/{slug}',['as'=>'media.news.single','uses'=>'MediaController@single']);

    Route::get('/hospital-campaigns',['as'=>'media.campaigns','uses'=>'MediaController@campaigns']);
    Route::get('/hospital-campaigns/{slug}',['as'=>'media.campaigns.single','uses'=>'MediaController@single']);

    Route::get('/seminars-and-workshops',['as'=>'media.seminars','uses'=>'MediaController@seminars']);
    Route::get('/seminars-and-workshops/{slug}',['as'=>'media.seminars.single','uses'=>'MediaController@singleEvent']);

    Route::group(['prefix' => 'galleries'], function() {
        Route::get('/', ['as' => 'pages.media.album', 'uses' => 'MediaController@galleries']);
        Route::get('/{slug}', ['as' => 'pages.media.album.single', 'uses' => 'MediaController@album']);
    });
});

Route::group(['prefix' => 'events'], function() {
    Route::get('/',['as'=>'events.index','uses'=>'EventController@index']);
    Route::get('/upcoming',['as'=>'events.upcoming','uses'=>'EventController@index']);
    Route::get('/past',['as'=>'events.past','uses'=>'EventController@past']);
    Route::get('/{slug}',['as'=>'events.single','uses'=>'EventController@show']);
});

Route::group(['prefix' => 'surveys'], function() {
    Route::get('/',['as'=>'surveys.index','uses'=>'SurveyController@index']);
    Route::get('/{slug}',['as'=>'surveys.single','uses'=>'SurveyController@show']);
    Route::post('/store',['as'=>'surveys.store','uses'=>'SurveyController@store']);
});

Route::get('/page/{slug}',['as'=>'page.single','uses'=>'MediaController@singlePage']);

Route::group(['prefix' => 'cp'], function() {

    Route::get('/',function(){ return redirect()->route('admin.login'); });
    Route::post('/login-post',['as'=>'admin.login.validate','uses'=>'Auth\AuthController@login']);
    Route::get('/login',['as'=>'admin.login','uses'=>'AdminController@login','middleware' => 'guest']);
    Route::get('/logout',['as'=>'admin.logout','uses'=>'Auth\AuthController@logout']);

    Route::group(['prefix' => 'articles','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.articles.index','uses'=>'AdminController@articles']);
        Route::get('/create',               ['as'=>'admin.articles.create','uses'=>'Admin\ArticleController@create']);
        Route::post('/store',               ['as'=>'admin.articles.store','uses'=>'Admin\ArticleController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.articles.edit','uses'=>'Admin\ArticleController@edit']);
        Route::post('/update',              ['as'=>'admin.articles.update','uses'=>'Admin\ArticleController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.articles.delete','uses'=>'Admin\ArticleController@delete']);
        Route::get('/category/{category}',  ['as'=>'admin.articles.get','uses'=>'Admin\ArticleController@index']);
    });

    Route::group(['prefix' => 'physicians','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.physicians.index','uses'=>'AdminController@physicians']);
        Route::get('/create',               ['as'=>'admin.physicians.create','uses'=>'Admin\PhysicianController@create']);
        Route::post('/store',               ['as'=>'admin.physicians.store','uses'=>'Admin\PhysicianController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.physicians.edit','uses'=>'Admin\PhysicianController@edit']);
        Route::post('/update',              ['as'=>'admin.physicians.update','uses'=>'Admin\PhysicianController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.physicians.delete','uses'=>'Admin\PhysicianController@delete']);
        Route::get('/feature/{id}',          ['as'=>'admin.physicians.feature','uses'=>'Admin\PhysicianController@feature']);
        Route::get('/unfeature/{id}',          ['as'=>'admin.physicians.unfeature','uses'=>'Admin\PhysicianController@unfeature']);
    });

    Route::group(['prefix' => 'departments','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.departments.index','uses'=>'AdminController@departments']);
        Route::get('/create',               ['as'=>'admin.departments.create','uses'=>'Admin\DepartmentController@create']);
        Route::post('/store',               ['as'=>'admin.departments.store','uses'=>'Admin\DepartmentController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.departments.edit','uses'=>'Admin\DepartmentController@edit']);
        Route::post('/update',              ['as'=>'admin.departments.update','uses'=>'Admin\DepartmentController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.departments.delete','uses'=>'Admin\DepartmentController@delete']);
    });

    Route::group(['prefix' => 'insurances','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.insurances.index','uses'=>'AdminController@insurances']);
        Route::get('/create',               ['as'=>'admin.insurances.create','uses'=>'Admin\InsuranceController@create']);
        Route::post('/store',               ['as'=>'admin.insurances.store','uses'=>'Admin\InsuranceController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.insurances.edit','uses'=>'Admin\InsuranceController@edit']);
        Route::post('/update',              ['as'=>'admin.insurances.update','uses'=>'Admin\InsuranceController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.insurances.delete','uses'=>'Admin\InsuranceController@delete']);
    });

    Route::group(['prefix' => 'careers','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.careers.index','uses'=>'AdminController@careers']);
        Route::get('/create',               ['as'=>'admin.careers.create','uses'=>'Admin\CareerController@create']);
        Route::post('/store',               ['as'=>'admin.careers.store','uses'=>'Admin\CareerController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.careers.edit','uses'=>'Admin\CareerController@edit']);
        Route::post('/update',              ['as'=>'admin.careers.update','uses'=>'Admin\CareerController@update']);
        Route::get('/delete/{id}',          ['as'=>'admin.careers.delete','uses'=>'Admin\CareerController@delete']);
    });

    Route::group(['prefix' => 'tweets','middleware' => 'auth'], function() {
        Route::get('/',                     ['as'=>'admin.tweets.index','uses'=>'AdminController@tweets']);
        Route::get('/create',               ['as'=>'admin.tweets.create','uses'=>'Admin\TweetController@create']);
        Route::post('/store',               ['as'=>'admin.tweets.store','uses'=>'Admin\TweetController@store']);
        Route::get('/edit/{id}',            ['as'=>'admin.tweets.edit','uses'=>'Admin\TweetController@edit']);
        Route::post('/update',              ['as'=>'admin.tweets.update','uses'=>'Admin\TweetController@update']);

app/Models/Album.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;

class Album extends Model
{
    use SearchableTrait;

    /**
     * Searchable rules.
     *
     * @var array
     */
    protected $searchable = [
        'columns' => [
            'title' => 10
        ]
    ];


    protected $fillable = ['title','slug','description','type','created_at'];

    public $dates = ['created_at'];
    
    /**
     * An article has uploads.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function uploads()
    {
        return $this->morphOne('App\Models\Upload', 'uploadable');
    }

    /**
     * An article has uploads.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function contents()
    {
        return $this->hasMany('App\Models\AlbumContent');
    }


    /**
     * get Thumbnail Attrib
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getThumbnailAttribute()
    {
        $thumb = $this->uploads()->where('template', 'thumb')->first();

        return $thumb ? asset('public'.$thumb->url ) : 'http://placehold.it/320x240';
    }

}

app/Models/Physician.php
<?php

namespace App\Models;

use App\Repositories\Traits\Fetcher;
use Illuminate\Database\Eloquent\Model;

use App\Models\PhysicianMetaData;
use Nicolaslopezj\Searchable\SearchableTrait;

class Physician extends Model
{
    use SearchableTrait;

    /**
     * Searchable rules.
     *
     * @var array
     */
    protected $searchable = [
        'columns' => [
            'fname' => 10,
            'lname' => 10
        ]
    ];

    protected $fillable = ['fname','lname','slug','position','description','gender','department_id'];

    /**
     * A user has a profile.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function uploads()
    {
        return $this->morphOne('App\Models\Upload', 'uploadable');
    }

    /**
     * get Thumbnail Attrib
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getThumbnailAttribute()
    {
        $thumb = $this->uploads()->where('template', 'thumb')->first();

        return $thumb ? asset('public').$thumb->url : 'http://placehold.it/240x280';
    }

    /**
     * get Thumbnail Attrib
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function getThumbnailFullAttribute()
    {
        $thumb = $this->uploads()->where('template', 'full')->first();

        return $thumb ? asset('public').$thumb->url : 'http://placehold.it/240x280';
    }


    public function getIsFeaturedAttribute()
    {
        $option = Option::where('slug','featured-physician')->where('value',$this->id)->first();

        return $option ? true : false;
    }


    public function getNameAttribute()
    {
        return $this->fname . ' ' . $this->lname;
    }

    public function department(){
        return $this->belongsToMany('App\Models\Department','physician_departments');
    }

    public function meta(){
        return $this->belongsToMany('App\Models\PhysicianMetaType','physician_meta_data','physician_id','meta_type_id');
    }

    public function getMeta($type){
        $meta = PhysicianMetaType::where('slug',$type)->first();
        return PhysicianMetaData::where('physician_id',$this->id)->where('meta_type_id',$meta->id)->get();
    }

    public function getDepartmentIdAttribute(){
        return $this->department()->first() ? $this->department()->first()->id : null;
    }

    public function getContactNumberAttribute(){
        $meta = PhysicianMetaType::where('slug','contact-number')->first();

        if($meta){
            $data = PhysicianMetaData::where('physician_id',$this->id)->where('meta_type_id',$meta->id)->first();

            if($data)
                return $data->value;
        }

        return null;
    }

    public function getSpecialtyAttribute(){

        if(!count($this->department))
            return null;

        $data = $this->department->first()->name;

        return $data ? $data : null;
    }
}

resources/views/templates/sidebar/doctors.blade.php
<div class="widget margin-t-20">
    <ul class="doctor-list">
        @inject('physFetcher', 'App\Services\PhysicianFetcher')

        <?php
        $physicians = [];
        $head = null;
        $subhead = null;

        if(isset($department)){

            $head = $department->head;
            $subhead = $department->subhead;

            if(count($department->physicians)){

                $physicians = [];

                foreach ($department->physicians as $data){

                    if($head){
                        if($data->id != $head->id)
                            $physicians[] = $data;
                    } else {
                        $physicians[] = $data;
                    }

//                        if(count($physicians)>4){
//                            break;
//                        }
                }
            }
        }
        //            else
        //                $physicians = $physFetcher->getLimit(3);

        ?>

        @if($head)
            <li class="col-md-12 col-sm-4 col-xs-6 padding-r-0">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <div class="row">
                            <a href="{{ route('physician.single',$head->slug) }}"><img src="{{ $head->thumbnail }}" width="100%"></a>
                        </div>
                    </div>
                    <div class="col-md-8 col-sm-8 col-xs-12">
                        <h1><a href="{{ route('physician.single',$head->slug) }}">{{ $head->name }}</a></h1>
                        {!! $head->specialty  !!} - Head of Department
                        @if(isset($department))
                            @if($department->id==17 && $head->id == 9)
                                (Orthopedics)
                            @endif
                        @endif
                    </div>
                </div>
            </li>
        @endif


        @if($subhead)
            <li class="col-md-12 col-sm-4 col-xs-6 padding-r-0">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <div class="row">
                            <a href="{{ route('physician.single',$subhead->slug) }}"><img src="{{ $subhead->thumbnail }}" width="100%"></a>
                        </div>
                    </div>
                    <div class="col-md-8 col-sm-8 col-xs-12">
                        <h1><a href="{{ route('physician.single',$subhead->slug) }}">{{ $subhead->name }}</a></h1>
                        {!! $subhead->specialty  !!}
                    </div>
                </div>
            </li>
        @endif


        @forelse($physicians as $physician)
            <li class="col-md-12 col-sm-4 col-xs-6 padding-r-0">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <div class="row">
                            <a href="{{ route('physician.single',$physician->slug) }}"><img src="{{ $physician->thumbnail }}" width="100%"></a>
                        </div>
                    </div>
                    <div class="col-md-8 col-sm-8 col-xs-12">
                        <h1><a href="{{ route('physician.single',$physician->slug) }}">{{ $physician->name }}</a></h1>
                        {!! $physician->specialty  !!}
                        @if(isset($department))
                            @if($department->id==17 && $physician->id == 9)
                                - Head of Department (Orthopedics)
                            @elseif($department->id==17 && $physician->id == 44)
                                - Head of Department (Spine)
                            @endif
                        @endif

                    </div>
                </div>
            </li>
        @empty
        @endforelse
    </ul>
</div>

resources/views/templates/sidebar/help.blade.php
<div class="help-box clearfix brownish-bg">
    <h1>Let Us Help You</h1>
    <ul id="help-icon-list">
        <li><a href="mailto:info@healthpoint.ae"><span class="icon-text phone">Contact Us</span></a></li>
        <li><a href="{{ url('request-appointment') }}"><span class="icon-text calendar">Make an appointment</span></a> </li>
        <li><a href="{{ url('find-a-doctor') }}"><span class="icon-text doctor">Find a physician</span></a> </li>
        <li><a href="{{ url('clinical-services') }}"><span class="icon-text search">Find a service</span></a> </li>
        <li><a href="{{ url('patients/insurance') }}"><span class="icon-text insurance">Insurance information</span></a> </li>
    </ul>
</div>

resources/views/templates/sidebar/insurance-info.blade.php
<div class="clearfix widget">
    <h1 class="panel-title">Insurance Info</h1>


    @inject('optionFetcher','App\Services\OptionFetcher')

    <div class="col-md-12">
        <div class="row padding-t-0">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" class="collapsed">
                                General</a>
                        </h4>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse">
                        <div class="panel-body">
                            {!! str_replace("&nbsp;"," ",$optionFetcher->getBySlug('insurance-general')) !!}
                        </div>
                    </div>
                </div>



                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse2" class="collapsed">
                                Inpatient Services</a>
                        </h4>
                    </div>
                    <div id="collapse2" class="panel-collapse collapse">
                        <div class="panel-body">
                            {!! str_replace("&nbsp;"," ",$optionFetcher->getBySlug('insurance-in')) !!}
                        </div>
                    </div>
                </div>



                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                                Outpatient Services</a>
                        </h4>
                    </div>
                    <div id="collapse3" class="panel-collapse collapse in">
                        <div class="panel-body">
                            {!! str_replace("&nbsp;"," ",$optionFetcher->getBySlug('insurance-out')) !!}
                        </div>
                    </div>
                </div>



                </div>
            </div>
        </div>
    </div>
</div>

resources/views/templates/sidebar/media-contacts.blade.php
@inject('optionFetcher','App\Services\OptionFetcher')

<?php
    $contact = $optionFetcher->getBySlug('media-contact');
?>

<div class="widget">
    <h1 class="panel-title">Media Contacts</h1>
    <div  class="padding-l-0 padding-r-0">
        {!! $contact ? $contact : '' !!}
    </div>
</div>

resources/views/templates/sidebar/media-pack.blade.php
{{--<div class="widget">--}}
    {{--<h1 class="panel-title">Media Pack</h1>--}}
    {{--<div  class="padding-l-0 padding-r-0">--}}
        {{--<ul class="margin-t-10">--}}
            {{--<li>--}}
                {{--<input type="checkbox" id="c1" checked="checked" />--}}
                {{--<label for="c1">Press pack images</label>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<input type="checkbox" id="c2"/>--}}
                {{--<label for="c2">PDF</label>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<input type="checkbox" id="c3"/>--}}
                {{--<label for="c3">Logos</label>--}}
            {{--</li>--}}
        {{--</ul>--}}
        {{--<input type="submit" class="brown-text normal-bold" value="Download">--}}
    {{--</div>--}}
{{--</div>--}}

resources/views/templates/sidebar/more-news.blade.php
<div class="widget">
    <h1 class="panel-title">More News</h1>
    <div  class="padding-l-0 padding-r-0">
        @inject('articleFetcher', 'App\Services\ArticleFetcher')

        <?php $articles = $articleFetcher->getByCategory(5,5); ?>

        <ul class="post-list clearfix">
            @forelse($articles as $article)
                <li class="col-md-12 col-sm-6 col-xs-6">
                    <div class="col-md-3 col-sm-5 col-xs-5 padding-l-0">
                        <div class="row text-left">
                            <a href="{{ route('blog.single',$article->slug) }}"><img src="{{ $article->thumbnailSquare }}" width="100%"></a>
                        </div>
                    </div>
                    <div class="col-md-9 col-sm-7 col-xs-7 padding-r-0 padding-l-25">
                        <div class="row">
                            <a href="{{ route('blog.single',$article->slug) }}"><h1>{{ $article->title }}</h1></a>
                        </div>
                    </div>
                </li>
            @empty
            @endforelse
        </ul>
    </div>
</div>

resources/views/templates/sidebar/more.blade.php
<div class="widget">
    <h1 class="panel-title">More Health Tips</h1>
    <div  class="padding-l-0 padding-r-0">

        @inject('articleFetcher', 'App\Services\ArticleFetcher')

        <?php $articles = $articleFetcher->getByCategory(4,6); ?>
        <?php $current_article_id = isset($article) ? $article->id : 0; ?>

        <ul class="post-list clearfix">
            @forelse($articles as $article)

                @if($current_article_id)
                    @if($current_article_id != $article->id)
                    <li class="col-md-12 col-sm-6 col-xs-6">
                        <div class="col-md-3 col-sm-5 col-xs-4 padding-l-0">
                            <div class="row text-left">
                                <a href="{{ route('blog.single',$article->slug) }}"><img src="{{ $article->thumbnailSquare }}" width="100%"></a>
                            </div>
                        </div>
                        <div class="col-md-9 col-sm-7 col-xs-8 padding-r-0 padding-l-25">
                            <div class="row">
                                <a href="{{ route('blog.single',$article->slug) }}"><h1>{{ $article->title }}</h1></a>
                            </div>
                        </div>
                    </li>
                    @endif
                @endif
            @empty
            @endforelse
        </ul>
    </div>
</div>

resources/views/templates/sidebar/most-popular.blade.php
<div class="widget">
    <h1 class="brown-header">Most Popular</h1>
    <div  class="padding-l-0 padding-r-0">

        @inject('articleFetcher', 'App\Services\ArticleFetcher')

        <?php $articles = $articleFetcher->getByCategoryPopular(4,10); ?>

        <ul class="popular-list clearfix">
            @foreach($articles as $index=>$article)
                <li class="col-md-12 col-sm-6 col-xs-6">
                    <div class="col-md-1 col-sm-1 col-xs-1 padding-l-0">
                        <div class="row text-left">
                            <span class="rank">{{ $index+1 }}</span>
                        </div>
                    </div>
                    <div class="col-md-11 col-sm-9 col-xs-9 padding-r-0 padding-l-25">
                        <div class="row">
                            <a href="{{ route('blog.single',$article->slug) }}"><h1>{{ $article->title }}</h1></a>
                        </div>
                    </div>
                </li>
            @endforeach
        </ul>
    </div>
</div>

resources/views/templates/sidebar/news.blade.php
<div class="clearfix widget">
    <h1 class="panel-title">Health News</h1>
    <div class="col-md-12">
        <div class="row padding-t-0">
            <ul class="article-list">
                @inject('articleFetcher', 'App\Services\ArticleFetcher')

                <?php $articles = $articleFetcher->getByCategory(5,3); ?>

                @forelse($articles as $article)
                    <li class="col-md-12 col-sm-6 col-xs-6 col-xxs-12">
                        <div class="row">
                                <div class="col-md-5 col-sm-5 col-xs-5 padding-l-0">
                                    <a href="{{ route('media.news.single',$article->slug) }}">
                                        <img src="{{ $article->thumbnailSquare }}" width="95%">
                                    </a>
                                </div>
                                <div class="col-md-7 col-sm-7 col-xs-7">
                                    <div class="row">
                                        <a href="{{ route('media.news.single',$article->slug) }}"><h1>{{ $article->title }}</h1></a>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </li>
                @empty
                    <li class="col-md-12 col-sm-6 col-xs-6 col-xxs-12">
                        <div class="row">
                            None
                        </div>
                    </li>
                @endforelse

                {{--<li class="col-md-12 col-sm-6 col-xs-6">--}}
                    {{--<div class="row">--}}
                            {{--<div class="col-md-5 col-sm-5 col-xs-5 padding-l-0">--}}
                                {{--<a href="#">--}}
                                    {{--<img src="{{ asset('public/images/placeholders/square-sm.jpg') }}" width="95%">--}}
                                {{--</a>--}}
                            {{--</div>--}}
                            {{--<div class="col-md-7 col-sm-7 col-xs-7 padding-r-0">--}}
                                {{--<div class="row">--}}
                                    {{--<a href="#"><h1>Simusam fugia nimusEhent</h1></a>--}}
                                    {{--<p>As aut lab incid excea di necerit fugiant officabo...</p>--}}
                                {{--</div>--}}
                            {{--</div>--}}
                        {{--</a>--}}
                    {{--</div>--}}
                {{--</li>--}}
            </ul>
        </div>
    </div>
</div>

resources/views/templates/sidebar/patient-rights.blade.php
<div class="clearfix widget">
    <h1 class="panel-title">Patient Rights</h1>


    @inject('optionFetcher','App\Services\OptionFetcher')

    <div class="col-md-12">
        <div class="row padding-t-0">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" class="collapsed">
                                Healthpoint patients and their families have the right:</a>
                        </h4>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse">
                        <div class="panel-body can-have-lists">
                            {!! str_replace("&nbsp;"," ",$optionFetcher->getBySlug('patient-rights')) !!}
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                                Healthpoint patients and their families are responsible to:</a>
                        </h4>
                    </div>
                    <div id="collapse2" class="panel-collapse collapse in">
                        <div class="panel-body can-have-lists">
                            {!! str_replace("&nbsp;"," ",$optionFetcher->getBySlug('patient-responsibilities')) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/templates/sidebar/share.blade.php
<div class="col-md-12 clearfix">
    <div class="row clearfix">
        <h1 class="panel-title padding-b-5">Share on</h1>
        <div  class="padding-l-0 padding-r-0">
            <ul class="share-list pull-left width-full margin-b-0">
                <li><a class="st_facebook_large share-icon-text fb relative" href="#">Facebook</a></li>
                <li><a class="st_twitter_large share-icon-text tw relative" href="#">Twitter</a></li>
                <li><a class="st_linkedin_large share-icon-text lk relative" href="#">LinkedIn</a></li>
                <li><a href="mailto:?subject=I wanted you to see this site&amp;body=Check out this site {{ \Illuminate\Support\Facades\Request::fullUrl() }}" class="st_email_large share-icon-text em relative">E-mail</a></li>
            </ul>
        </div>
    </div>
</div>